/* Generated By:JavaCC: Do not edit this line. Pl1ParserTreeConstants.java Version 7.0.12 */
package pl1transpiler;

public interface Pl1ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVAR = 1;
  public int JJTMINOR = 2;
  public int JJTSCOPE = 3;
  public int JJTTYPE = 4;
  public int JJTSTRING = 5;
  public int JJTDECIMAL = 6;
  public int JJTBINARY = 7;
  public int JJTSIZE = 8;
  public int JJTINT = 9;
  public int JJTDOUBLE = 10;
  public int JJTID = 11;


  public String[] jjtNodeName = {
    "PROGRAM",
    "VAR",
    "MINOR",
    "SCOPE",
    "TYPE",
    "STRING",
    "DECIMAL",
    "BINARY",
    "size",
    "INT",
    "DOUBLE",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=24f15baf1f7918f7382461f913a42f88 (do not edit this line) */
