/* Generated By:JJTree&JavaCC: Do not edit this line. Pl1ParserConstants.java */
package pl1transpiler.Pl1Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Pl1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DECLARE = 1;
  /** RegularExpression Id. */
  int DCL = 2;
  /** RegularExpression Id. */
  int DECIMAL = 3;
  /** RegularExpression Id. */
  int BIN = 4;
  /** RegularExpression Id. */
  int BINARY = 5;
  /** RegularExpression Id. */
  int CHAR = 6;
  /** RegularExpression Id. */
  int REAL = 7;
  /** RegularExpression Id. */
  int COMPLEX = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int UNSIGNED = 10;
  /** RegularExpression Id. */
  int SIGNED = 11;
  /** RegularExpression Id. */
  int FIXED = 12;
  /** RegularExpression Id. */
  int ATTRIBUTE = 13;
  /** RegularExpression Id. */
  int SINGLE_ATTRIBUTE = 14;
  /** RegularExpression Id. */
  int PL1_WORD = 15;
  /** RegularExpression Id. */
  int EOL = 16;
  /** RegularExpression Id. */
  int SPACE_SEPARATOR = 17;
  /** RegularExpression Id. */
  int SPACECHAR = 18;
  /** RegularExpression Id. */
  int INTEGER = 19;
  /** RegularExpression Id. */
  int SCOPE = 20;
  /** RegularExpression Id. */
  int MINUSCHAR = 21;
  /** RegularExpression Id. */
  int PREPROC_COMMENT = 22;
  /** RegularExpression Id. */
  int COMMA_SEPARATOR = 23;
  /** RegularExpression Id. */
  int COMMENT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"DECLARE\"",
    "\"DCL\"",
    "\"DECIMAL\"",
    "\"BIN\"",
    "\"BINARY\"",
    "\"CHAR\"",
    "\"REAL\"",
    "\"COMPLEX\"",
    "\"FLOAT\"",
    "\"UNSIGNED\"",
    "\"SIGNED\"",
    "\"FIXED\"",
    "<ATTRIBUTE>",
    "<SINGLE_ATTRIBUTE>",
    "<PL1_WORD>",
    "\"\\n\"",
    "<SPACE_SEPARATOR>",
    "<SPACECHAR>",
    "<INTEGER>",
    "<SCOPE>",
    "\"-\"",
    "<PREPROC_COMMENT>",
    "<COMMA_SEPARATOR>",
    "<COMMENT>",
  };

}
